### ISSUE TITLE
Public cloud: Move a how-to guide from a specific cloud to a more generic location 

### ISSUE THREAD

**Issue by k-dimple** [canonical/open-documentation-academy#31] opened 2024-03-08 11:14 UTC
GitHub repo: https://github.com/canonical/ubuntu-cloud-docs

The repo contains multiple projects (one per cloud and a generic one called 'all-clouds'). A specific how-to guide under the 'google' project ([Check if your Ubuntu image has addressed a CVE](https://github.com/canonical/ubuntu-cloud-docs/blob/main/google/google-how-to/gce/check-cve-on-instance.rst)) needs to be moved to the 'all-clouds' project since the instructions in the how-to guide are generic and applicable to all clouds.

**Comment by activus-d** [comment] 2024-03-08 12:07
@k-dimple I'd like to work on this issue.

**Comment by k-dimple** [comment] 2024-03-08 16:11
Sure @activus-d that'll be great! Please give it a go and let me know if you have any questions.

The 'all-clouds' project does not include a 'how-to' section and we won't be creating that till we get more content. So currently you can add this how-to guide to the main list of content that you see on the left navigation bar on the [published version of all-clouds](https://canonical-public-cloud.readthedocs-hosted.com/en/latest/)

**Comment by k-dimple** [comment] 2024-03-10 06:22
Also @activus-d, you might want to check out the contribution guidelines for these projects in case it helps:
* [How to contribute to the 'all-clouds' project](https://canonical-public-cloud.readthedocs-hosted.com/en/latest/all-clouds-how-to/contribute-to-these-docs/)
* [How to contribute to the 'google' project](https://canonical-gcp.readthedocs-hosted.com/en/latest/google-how-to/contribute-to-these-docs/)

**Comment by activus-d** [comment] 2024-03-11 14:00
> Also @activus-d, you might want to check out the contribution guidelines for these projects in case it helps:
> 
> * [How to contribute to the 'all-clouds' project](https://canonical-public-cloud.readthedocs-hosted.com/en/latest/all-clouds-how-to/contribute-to-these-docs/)
> * [How to contribute to the 'google' project](https://canonical-gcp.readthedocs-hosted.com/en/latest/google-how-to/contribute-to-these-docs/)

They will surely be helpful. Thanks for sharing @k-dimple

**Comment by activus-d** [comment] 2024-03-11 18:49
@k-dimple While trying to run checks on the new changes I made to the documentation, the `PROJECT=all-clouds make woke` command prompted me to enter a password:

```
Installing "woke" snap... 

Password:
```

**Comment by k-dimple** [comment] 2024-03-11 19:40
Assuming that you are running the checks on your local machine, it should be the password of the logged in user (i.e. you?). Just use the password that you would use whenever you try to install any package.

**Comment by activus-d** [comment] 2024-03-11 21:13
Yes, I was running the checks on my local machine and used my password but got the error:

```
Installing "woke" snap... 

Password:
sudo: snap: command not found
make: *** [woke-install] Error 1
```

Subsequently, I downloaded `Snapcraft` by following the instructions on [Install snapcraft on macOS](https://snapcraft.io/docs/installing-snapcraft). I then rerun the `PROJECT=all-clouds make woke command`, but got the error:

```
Installing "woke" snap... 

Password:
Interacting with snapd is not yet supported on darwin.
This command has been left available for documentation purposes only.
make: *** [woke-install] Error 1
```

My finding from this [Snapcraft forum](https://forum.snapcraft.io/t/error-installing-other-packages-via-snap/21420) show that Snapcraft is not supported by my MacOS and may be interfering with running the `PROJECT=all-clouds make woke` command. Do you think I should make a PR regardless? I would also appreciate any help I can get with solving this issue.

**Comment by k-dimple** [comment] 2024-03-12 10:10
Yeah, I think you can go ahead and create the PR. All the tests (including woke) will anyway run as part of the PR checks.

@degville would you be able to help with the above issue (related to installing snaps on MacOS) that @activus-d is facing?

**Comment by activus-d** [comment] 2024-03-12 11:58
@k-dimple I have created a [pull request](https://github.com/canonical/ubuntu-cloud-docs/pull/187) to solve this issue.

**Comment by degville** [comment] 2024-03-12 13:39
> @degville would you be able to help with the above issue (related to installing snaps on MacOS) that @activus-d is facing?

Yes, of course. I know what the problem is - I'll try and have a closer look later. Thanks for including me!

**Comment by degville** [comment] 2024-03-12 23:07
> > @degville would you be able to help with the above issue (related to installing snaps on MacOS) that @activus-d is facing?
> 
> Yes, of course. I know what the problem is - I'll try and have a closer look later. Thanks for including me!

I don't think there's a quick fix for this. Our Makefile only currently installs woke from its snap, which precludes non-snap-capable systems including macOS and Windows. There are other installation methods for woke (brew on macOS, for example). But I think the best solution is likely to move away from woke completely, and incorporate its wordlist into aspell or some of our other tooling. This may even be a good task for the Academy.

**Closed** 2024-03-13 08:54 UTC
Labels: edit, size 1, update
